server:
  port: 10001
spring:
  application:
    name: taobao-registry
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10001/eureka
      register-with-eureka: false #不注册自己
      fetch-registry: false #不拉取注册信息